FROM python:3.9-slim

WORKDIR /app

COPY ./stack-1/api/requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY ./stack-1/api .

RUN ls -la /app

CMD ["python", "app.py"]

EXPOSE 5001