openapi: 3.0.0
info:
  title: Python API Test
  description: API TEST
  version: '1.0'

servers:
  - url: "{protocol}://{server_name}:{server_port}"
    variables:
      protocol:
        enum:
          - http
          - https
        default: http
      server_name:
        default: 0.0.0.0
      server_port:
        default: "5001"

paths:
  /register:
    post:
      summary: Register user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: "username"
                password:
                  type: string
                  example: "password"
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Error in input data
        '500':
          description: Server error

  /login:
    post:
      summary: Log in
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: "username"
                password:
                  type: string
                  example: "password"
      responses:
        '200':
          description: Login successful
        '401':
          description: Invalid credentials
        '500':
          description: Server error

  /messages:
    get:
      summary: Get messages
      security:
        - BearerAuth: []
      responses:
        '200':
          description: List of messages
        '401':
          description: Unauthorized
        '500':
          description: Server error
    post:
      summary: Create message
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                  example: "Hello, world!"
      responses:
        '201':
          description: Message created successfully
        '400':
          description: Error in input data
        '401':
          description: Unauthorized
        '500':
          description: Server error

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
