version: '3.8'

services:
  nginx-proxy:
    image: nginx:latest
    ports:
      - "80:80"
      - "9000:9000"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - test-devops-network

networks:
  test-devops-network:
    external: true
